-- MySQL Script generated by MySQL Workbench
-- Dom 05 Fev 2017 13:37:25 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Teste_Interativa
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Teste_Interativa
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Teste_Interativa` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `Teste_Interativa` ;

-- -----------------------------------------------------
-- Table `Teste_Interativa`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teste_Interativa`.`categorias` ;

CREATE TABLE IF NOT EXISTS `Teste_Interativa`.`categorias` (
  `ID_CATEGORIA` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `NOME` VARCHAR(50) NOT NULL COMMENT '',
  `DATA_FECHA` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ID_CATEGORIA`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teste_Interativa`.`posts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teste_Interativa`.`posts` ;

CREATE TABLE IF NOT EXISTS `Teste_Interativa`.`posts` (
  `ID_POST` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_CATEGORIA` INT NOT NULL COMMENT '',
  `TITULO` VARCHAR(50) NOT NULL COMMENT '',
  `SUBTITULO` VARCHAR(100) NOT NULL COMMENT '',
  `TEXTO` TEXT NOT NULL COMMENT '',
  `TIMESTAMP` VARCHAR(20) NOT NULL COMMENT '',
  `DATA_FECHA` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ID_POST`)  COMMENT '',
  INDEX `ID_CATEGORIA_FK_idx` (`ID_CATEGORIA` ASC)  COMMENT '',
  CONSTRAINT `ID_CATEGORIA_FK`
    FOREIGN KEY (`ID_CATEGORIA`)
    REFERENCES `Teste_Interativa`.`categorias` (`ID_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Teste_Interativa`.`comentarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Teste_Interativa`.`comentarios` ;

CREATE TABLE IF NOT EXISTS `Teste_Interativa`.`comentarios` (
  `ID_COMENTARIO` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_POST` INT NOT NULL COMMENT '',
  `NOME` VARCHAR(50) NOT NULL COMMENT '',
  `EMAIL` VARCHAR(100) NOT NULL COMMENT '',
  `MENSAGEM` VARCHAR(1000) NOT NULL COMMENT '',
  `IP` VARCHAR(15) NOT NULL COMMENT '',
  `TIMESTAMP` VARCHAR(20) NOT NULL COMMENT '',
  `DATA_FECHA` VARCHAR(20) NULL COMMENT '',
  PRIMARY KEY (`ID_COMENTARIO`)  COMMENT '',
  INDEX `ID_POST)FK_idx` (`ID_POST` ASC)  COMMENT '',
  CONSTRAINT `ID_POST)FK`
    FOREIGN KEY (`ID_POST`)
    REFERENCES `Teste_Interativa`.`posts` (`ID_POST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `Teste_Interativa`.`categorias`
-- -----------------------------------------------------
START TRANSACTION;
USE `Teste_Interativa`;
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (1, 'Tecnologia', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (2, 'Internet', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (3, 'Jogos', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (4, 'Música', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (5, 'Bem-estar', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (6, 'Esportes', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (7, 'Beleza', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (8, 'Moda', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (9, 'Trabalho', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (10, 'Desenvolvimento pessoal', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (11, 'Finanças', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (12, 'Lazer', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (13, 'Viagem', NULL);
INSERT INTO `Teste_Interativa`.`categorias` (`ID_CATEGORIA`, `NOME`, `DATA_FECHA`) VALUES (14, 'Família', NULL);

COMMIT;

